/*
 * VILT Connector
 *
 * Edge virtual Instructor Led Training (vILT) API Template. Use this template to help generate your API contracts so that you can connect with CSOD and become a vILT provider. Detailed in this API are endpoints that should be implemented so that the contract can adhere to Edge vILT Provider standards.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
//

namespace vILT.Domain
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AddInstructorRequest : IEquatable<AddInstructorRequest>
    { 
        /// <summary>
        /// Instructor&#39;s email address
        /// </summary>
        /// <value>Instructor&#39;s email address</value>
        [Required]
        [DataMember(Name="Email")]
        public string Email { get; set; }

        /// <summary>
        /// Instructor&#39;s first name
        /// </summary>
        /// <value>Instructor&#39;s first name</value>
        [Required]
        [DataMember(Name="FirstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// Instructor&#39;s last name
        /// </summary>
        /// <value>Instructor&#39;s last name</value>
        [Required]
        [DataMember(Name="LastName")]
        public string LastName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AddInstructorRequest {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        //public string ToJson()
        //{
        //    //return JsonConvert.SerializeObject(this, Formatting.Indented);
        //}

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AddInstructorRequest)obj);
        }

        /// <summary>
        /// Returns true if AddInstructorRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of AddInstructorRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddInstructorRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Email == other.Email ||
                    Email != null &&
                    Email.Equals(other.Email)
                ) && 
                (
                    FirstName == other.FirstName ||
                    FirstName != null &&
                    FirstName.Equals(other.FirstName)
                ) && 
                (
                    LastName == other.LastName ||
                    LastName != null &&
                    LastName.Equals(other.LastName)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Email != null)
                    hashCode = hashCode * 59 + Email.GetHashCode();
                    if (FirstName != null)
                    hashCode = hashCode * 59 + FirstName.GetHashCode();
                    if (LastName != null)
                    hashCode = hashCode * 59 + LastName.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(AddInstructorRequest left, AddInstructorRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AddInstructorRequest left, AddInstructorRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
