/*
 * VILT Connector
 *
 * Edge virtual Instructor Led Training (vILT) API Template. Use this template to help generate your API contracts so that you can connect with CSOD and become a vILT provider. Detailed in this API are endpoints that should be implemented so that the contract can adhere to Edge vILT Provider standards.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;


namespace vILT.Domain
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ViltConnectorError : IEquatable<ViltConnectorError>
    { 
        /// <summary>
        /// Error code. Accepted values include 400 (InvalidData), 401 (Unauthorized), 403 (Forbidden), 404 (ResourceNotFound), and 500 (SystemError).
        /// </summary>
        /// <value>Error code. Accepted values include 400 (InvalidData), 401 (Unauthorized), 403 (Forbidden), 404 (ResourceNotFound), and 500 (SystemError).</value>
        [Required]
        [DataMember(Name="code")]
        public int? Code { get; set; }

        /// <summary>
        /// Descriptive message explaining the error. This message is displayed in the Cornerstone UI to the end user.
        /// </summary>
        /// <value>Descriptive message explaining the error. This message is displayed in the Cornerstone UI to the end user.</value>
        [Required]
        [DataMember(Name="message")]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ViltConnectorError {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        //public string ToJson()
        //{
        //    //return JsonConvert.SerializeObject(this, Formatting.Indented);
        //}

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ViltConnectorError)obj);
        }

        /// <summary>
        /// Returns true if ViltConnectorError instances are equal
        /// </summary>
        /// <param name="other">Instance of ViltConnectorError to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ViltConnectorError other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Code == other.Code ||
                    Code != null &&
                    Code.Equals(other.Code)
                ) && 
                (
                    Message == other.Message ||
                    Message != null &&
                    Message.Equals(other.Message)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Code != null)
                    hashCode = hashCode * 59 + Code.GetHashCode();
                    if (Message != null)
                    hashCode = hashCode * 59 + Message.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ViltConnectorError left, ViltConnectorError right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ViltConnectorError left, ViltConnectorError right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
